/*
 * This file is generated by jOOQ.
 */
package com.d3rrick.ledgercore.repository.jooq.tables.records;


import com.d3rrick.ledgercore.repository.jooq.tables.Loan;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LoanRecord extends UpdatableRecordImpl<LoanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.loan.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.loan.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.loan.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.loan.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.loan.status</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.loan.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.loan.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.loan.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoanRecord
     */
    public LoanRecord() {
        super(Loan.LOAN);
    }

    /**
     * Create a detached, initialised LoanRecord
     */
    public LoanRecord(UUID userId, BigDecimal amount, String status, LocalDateTime createdAt) {
        super(Loan.LOAN);

        setUserId(userId);
        setAmount(amount);
        setStatus(status);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }
}
