/*
 * This file is generated by jOOQ.
 */
package com.d3rrick.ledgercore.repository.jooq;


import com.d3rrick.ledgercore.repository.jooq.tables.Loan;
import com.d3rrick.ledgercore.repository.jooq.tables.records.LoanRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LoanRecord> LOAN_PKEY = Internal.createUniqueKey(Loan.LOAN, DSL.name("loan_pkey"), new TableField[] { Loan.LOAN.USER_ID }, true);
}
