/*
 * This file is generated by jOOQ.
 */
package com.d3rrick.ledgercore.repository.jooq;


import com.d3rrick.ledgercore.repository.jooq.tables.Loan;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.loan</code>.
     */
    public static final Loan LOAN = Loan.LOAN;
}
