/*
 * This file is generated by jOOQ.
 */
package com.d3rrick.ledgercore.infrastructure.jooq.tables.records;


import com.d3rrick.ledgercore.infrastructure.jooq.tables.LedgerEntry;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LedgerEntryRecord extends UpdatableRecordImpl<LedgerEntryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ledger_entry.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ledger_entry.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.ledger_entry.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ledger_entry.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.ledger_entry.amount_delta</code>.
     */
    public void setAmountDelta(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ledger_entry.amount_delta</code>.
     */
    public BigDecimal getAmountDelta() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.ledger_entry.entry_type</code>.
     */
    public void setEntryType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ledger_entry.entry_type</code>.
     */
    public String getEntryType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.ledger_entry.idempotency_key</code>.
     */
    public void setIdempotencyKey(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ledger_entry.idempotency_key</code>.
     */
    public UUID getIdempotencyKey() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.ledger_entry.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ledger_entry.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LedgerEntryRecord
     */
    public LedgerEntryRecord() {
        super(LedgerEntry.LEDGER_ENTRY);
    }

    /**
     * Create a detached, initialised LedgerEntryRecord
     */
    public LedgerEntryRecord(Long id, UUID userId, BigDecimal amountDelta, String entryType, UUID idempotencyKey, OffsetDateTime createdAt) {
        super(LedgerEntry.LEDGER_ENTRY);

        setId(id);
        setUserId(userId);
        setAmountDelta(amountDelta);
        setEntryType(entryType);
        setIdempotencyKey(idempotencyKey);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }
}
