/*
 * This file is generated by jOOQ.
 */
package com.d3rrick.ledgercore.infrastructure.jooq.tables.records;


import com.d3rrick.ledgercore.infrastructure.jooq.tables.Loan;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LoanRecord extends UpdatableRecordImpl<LoanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.loan.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.loan.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.loan.principal_amount</code>.
     */
    public void setPrincipalAmount(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.loan.principal_amount</code>.
     */
    public BigDecimal getPrincipalAmount() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.loan.current_balance</code>.
     */
    public void setCurrentBalance(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.loan.current_balance</code>.
     */
    public BigDecimal getCurrentBalance() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.loan.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.loan.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.loan.version</code>.
     */
    public void setVersion(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.loan.version</code>.
     */
    public Long getVersion() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.loan.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.loan.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoanRecord
     */
    public LoanRecord() {
        super(Loan.LOAN);
    }

    /**
     * Create a detached, initialised LoanRecord
     */
    public LoanRecord(UUID userId, BigDecimal principalAmount, BigDecimal currentBalance, String status, Long version, OffsetDateTime updatedAt) {
        super(Loan.LOAN);

        setUserId(userId);
        setPrincipalAmount(principalAmount);
        setCurrentBalance(currentBalance);
        setStatus(status);
        setVersion(version);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
