/*
 * This file is generated by jOOQ.
 */
package com.d3rrick.ledgercore.infrastructure.jooq;


import com.d3rrick.ledgercore.infrastructure.jooq.tables.LedgerEntry;
import com.d3rrick.ledgercore.infrastructure.jooq.tables.Loan;
import com.d3rrick.ledgercore.infrastructure.jooq.tables.records.LedgerEntryRecord;
import com.d3rrick.ledgercore.infrastructure.jooq.tables.records.LoanRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LedgerEntryRecord> LEDGER_ENTRY_IDEMPOTENCY_KEY_KEY = Internal.createUniqueKey(LedgerEntry.LEDGER_ENTRY, DSL.name("ledger_entry_idempotency_key_key"), new TableField[] { LedgerEntry.LEDGER_ENTRY.IDEMPOTENCY_KEY }, true);
    public static final UniqueKey<LedgerEntryRecord> LEDGER_ENTRY_PKEY = Internal.createUniqueKey(LedgerEntry.LEDGER_ENTRY, DSL.name("ledger_entry_pkey"), new TableField[] { LedgerEntry.LEDGER_ENTRY.ID }, true);
    public static final UniqueKey<LoanRecord> LOAN_PKEY = Internal.createUniqueKey(Loan.LOAN, DSL.name("loan_pkey"), new TableField[] { Loan.LOAN.USER_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LedgerEntryRecord, LoanRecord> LEDGER_ENTRY__LEDGER_ENTRY_USER_ID_FKEY = Internal.createForeignKey(LedgerEntry.LEDGER_ENTRY, DSL.name("ledger_entry_user_id_fkey"), new TableField[] { LedgerEntry.LEDGER_ENTRY.USER_ID }, Keys.LOAN_PKEY, new TableField[] { Loan.LOAN.USER_ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
