/*
 * This file is generated by jOOQ.
 */
package com.d3rrick.ledgercore.infrastructure.jooq.tables;


import com.d3rrick.ledgercore.infrastructure.jooq.Keys;
import com.d3rrick.ledgercore.infrastructure.jooq.Public;
import com.d3rrick.ledgercore.infrastructure.jooq.tables.Loan.LoanPath;
import com.d3rrick.ledgercore.infrastructure.jooq.tables.records.LedgerEntryRecord;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LedgerEntry extends TableImpl<LedgerEntryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ledger_entry</code>
     */
    public static final LedgerEntry LEDGER_ENTRY = new LedgerEntry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LedgerEntryRecord> getRecordType() {
        return LedgerEntryRecord.class;
    }

    /**
     * The column <code>public.ledger_entry.id</code>.
     */
    public final TableField<LedgerEntryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.ledger_entry.user_id</code>.
     */
    public final TableField<LedgerEntryRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.ledger_entry.amount_delta</code>.
     */
    public final TableField<LedgerEntryRecord, BigDecimal> AMOUNT_DELTA = createField(DSL.name("amount_delta"), SQLDataType.NUMERIC(19, 2).nullable(false), this, "");

    /**
     * The column <code>public.ledger_entry.entry_type</code>.
     */
    public final TableField<LedgerEntryRecord, String> ENTRY_TYPE = createField(DSL.name("entry_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.ledger_entry.idempotency_key</code>.
     */
    public final TableField<LedgerEntryRecord, UUID> IDEMPOTENCY_KEY = createField(DSL.name("idempotency_key"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.ledger_entry.created_at</code>.
     */
    public final TableField<LedgerEntryRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private LedgerEntry(Name alias, Table<LedgerEntryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LedgerEntry(Name alias, Table<LedgerEntryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ledger_entry</code> table reference
     */
    public LedgerEntry(String alias) {
        this(DSL.name(alias), LEDGER_ENTRY);
    }

    /**
     * Create an aliased <code>public.ledger_entry</code> table reference
     */
    public LedgerEntry(Name alias) {
        this(alias, LEDGER_ENTRY);
    }

    /**
     * Create a <code>public.ledger_entry</code> table reference
     */
    public LedgerEntry() {
        this(DSL.name("ledger_entry"), null);
    }

    public <O extends Record> LedgerEntry(Table<O> path, ForeignKey<O, LedgerEntryRecord> childPath, InverseForeignKey<O, LedgerEntryRecord> parentPath) {
        super(path, childPath, parentPath, LEDGER_ENTRY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LedgerEntryPath extends LedgerEntry implements Path<LedgerEntryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LedgerEntryPath(Table<O> path, ForeignKey<O, LedgerEntryRecord> childPath, InverseForeignKey<O, LedgerEntryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LedgerEntryPath(Name alias, Table<LedgerEntryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LedgerEntryPath as(String alias) {
            return new LedgerEntryPath(DSL.name(alias), this);
        }

        @Override
        public LedgerEntryPath as(Name alias) {
            return new LedgerEntryPath(alias, this);
        }

        @Override
        public LedgerEntryPath as(Table<?> alias) {
            return new LedgerEntryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<LedgerEntryRecord, Long> getIdentity() {
        return (Identity<LedgerEntryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<LedgerEntryRecord> getPrimaryKey() {
        return Keys.LEDGER_ENTRY_PKEY;
    }

    @Override
    public List<UniqueKey<LedgerEntryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.LEDGER_ENTRY_IDEMPOTENCY_KEY_KEY);
    }

    @Override
    public List<ForeignKey<LedgerEntryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LEDGER_ENTRY__LEDGER_ENTRY_USER_ID_FKEY);
    }

    private transient LoanPath _loan;

    /**
     * Get the implicit join path to the <code>public.loan</code> table.
     */
    public LoanPath loan() {
        if (_loan == null)
            _loan = new LoanPath(this, Keys.LEDGER_ENTRY__LEDGER_ENTRY_USER_ID_FKEY, null);

        return _loan;
    }

    @Override
    public LedgerEntry as(String alias) {
        return new LedgerEntry(DSL.name(alias), this);
    }

    @Override
    public LedgerEntry as(Name alias) {
        return new LedgerEntry(alias, this);
    }

    @Override
    public LedgerEntry as(Table<?> alias) {
        return new LedgerEntry(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LedgerEntry rename(String name) {
        return new LedgerEntry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LedgerEntry rename(Name name) {
        return new LedgerEntry(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LedgerEntry rename(Table<?> name) {
        return new LedgerEntry(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LedgerEntry where(Condition condition) {
        return new LedgerEntry(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LedgerEntry where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LedgerEntry where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LedgerEntry where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LedgerEntry where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LedgerEntry where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LedgerEntry where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LedgerEntry where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LedgerEntry whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LedgerEntry whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
