/*
 * This file is generated by jOOQ.
 */
package com.d3rrick.ledgercore.infrastructure.jooq.tables;


import com.d3rrick.ledgercore.infrastructure.jooq.Keys;
import com.d3rrick.ledgercore.infrastructure.jooq.Public;
import com.d3rrick.ledgercore.infrastructure.jooq.tables.LedgerEntry.LedgerEntryPath;
import com.d3rrick.ledgercore.infrastructure.jooq.tables.records.LoanRecord;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Loan extends TableImpl<LoanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.loan</code>
     */
    public static final Loan LOAN = new Loan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LoanRecord> getRecordType() {
        return LoanRecord.class;
    }

    /**
     * The column <code>public.loan.user_id</code>.
     */
    public final TableField<LoanRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.loan.principal_amount</code>.
     */
    public final TableField<LoanRecord, BigDecimal> PRINCIPAL_AMOUNT = createField(DSL.name("principal_amount"), SQLDataType.NUMERIC(19, 2).nullable(false), this, "");

    /**
     * The column <code>public.loan.current_balance</code>.
     */
    public final TableField<LoanRecord, BigDecimal> CURRENT_BALANCE = createField(DSL.name("current_balance"), SQLDataType.NUMERIC(19, 2).nullable(false), this, "");

    /**
     * The column <code>public.loan.status</code>.
     */
    public final TableField<LoanRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.loan.version</code>.
     */
    public final TableField<LoanRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.loan.updated_at</code>.
     */
    public final TableField<LoanRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Loan(Name alias, Table<LoanRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Loan(Name alias, Table<LoanRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.loan</code> table reference
     */
    public Loan(String alias) {
        this(DSL.name(alias), LOAN);
    }

    /**
     * Create an aliased <code>public.loan</code> table reference
     */
    public Loan(Name alias) {
        this(alias, LOAN);
    }

    /**
     * Create a <code>public.loan</code> table reference
     */
    public Loan() {
        this(DSL.name("loan"), null);
    }

    public <O extends Record> Loan(Table<O> path, ForeignKey<O, LoanRecord> childPath, InverseForeignKey<O, LoanRecord> parentPath) {
        super(path, childPath, parentPath, LOAN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LoanPath extends Loan implements Path<LoanRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LoanPath(Table<O> path, ForeignKey<O, LoanRecord> childPath, InverseForeignKey<O, LoanRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LoanPath(Name alias, Table<LoanRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LoanPath as(String alias) {
            return new LoanPath(DSL.name(alias), this);
        }

        @Override
        public LoanPath as(Name alias) {
            return new LoanPath(alias, this);
        }

        @Override
        public LoanPath as(Table<?> alias) {
            return new LoanPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<LoanRecord> getPrimaryKey() {
        return Keys.LOAN_PKEY;
    }

    private transient LedgerEntryPath _ledgerEntry;

    /**
     * Get the implicit to-many join path to the
     * <code>public.ledger_entry</code> table
     */
    public LedgerEntryPath ledgerEntry() {
        if (_ledgerEntry == null)
            _ledgerEntry = new LedgerEntryPath(this, null, Keys.LEDGER_ENTRY__LEDGER_ENTRY_USER_ID_FKEY.getInverseKey());

        return _ledgerEntry;
    }

    @Override
    public Loan as(String alias) {
        return new Loan(DSL.name(alias), this);
    }

    @Override
    public Loan as(Name alias) {
        return new Loan(alias, this);
    }

    @Override
    public Loan as(Table<?> alias) {
        return new Loan(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Loan rename(String name) {
        return new Loan(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Loan rename(Name name) {
        return new Loan(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Loan rename(Table<?> name) {
        return new Loan(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Loan where(Condition condition) {
        return new Loan(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Loan where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Loan where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Loan where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Loan where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Loan where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Loan where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Loan where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Loan whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Loan whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
